server:
  port: 8103

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chatbot-config #指定服务名
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_bot?characterEncoding=UTF8
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    database: mysql
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka/
  instance:
    prefer-ip-address: true

